
version: "3.2"

services:

  frontend:
    image: 'arturzuravljov/frontend-angular-car-owners-registry:latest'      
    restart: always 
    ports:
      - 127.0.0.1:4200:80    
    command: npm run start

  backend:
    image: 'arturzuravljov/car-owners-registry-backend:latest'    
    depends_on:
      - db
    links:
      - db
    restart: always 
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/car_registry

  db:    
    image: 'postgres:13.4-alpine'     
    ports:
      - 5430:5432
    restart: always
    volumes:
      #- ./car-owners-registry-backend/docker/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car_registry
      
